
package com.reafmarketing.giftcardmanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GiftCardManagement", targetNamespace = "http://www.reafmarketing.com/GiftCardManagement/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GiftCardManagement {


    /**
     * 
     * @return
     *     returns com.reafmarketing.giftcardmanagement.ReportCompanyCard
     * @throws GiftCardException_Exception
     */
    @WebMethod
    @WebResult(name = "reportAccessCard", targetNamespace = "http://www.reafmarketing.com/GiftCardManagement/", partName = "result")
    public ReportCompanyCard reportAccessCard()
        throws GiftCardException_Exception
    ;

    /**
     * 
     * @param parameters
     * @throws GiftCardException_Exception
     */
    @WebMethod
    public void giftCardSelected(
        @WebParam(name = "companyCard", targetNamespace = "http://www.reafmarketing.com/GiftCardManagement/", partName = "parameters")
        CompanyCard parameters)
        throws GiftCardException_Exception
    ;

}
