
package com.reafmarketing.giftcardmanagement;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GiftCardException", targetNamespace = "http://www.reafmarketing.com/GiftCardManagement/")
public class GiftCardException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GiftCardException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GiftCardException_Exception(String message, GiftCardException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GiftCardException_Exception(String message, GiftCardException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.reafmarketing.giftcardmanagement.GiftCardException
     */
    public GiftCardException getFaultInfo() {
        return faultInfo;
    }

}
